[workspace]
members = [
    "pyrite-arm",
    "pyrite-common",
    "pyrite-gba",
    "pyrite",
    "imgui"
]

[profile.dev]
opt-level= 2
debug = false
debug-assertions = true

[profile.release]
opt-level= 3
debug = false
debug-assertions = false
